Update patch set 2
Patch Set 2:

Turns out [1] dexgen uses a Android API level 4 [2] which does not know about try-with-resources (introduced in 19). I refactored to ugly nested try/finally block. Can you please have another look?

[1] Build failed with:
FileUtils.java:74: The resource type FileInputStream does not implement java.lang.AutoCloseable
FileUtils.java:77: The type FileInputStream is not visible

[2] https://android.googlesource.com/platform/dalvik/+/master/dexgen/Android.mk

Patch-set: 2